version: 2
updates:
  # 1. Security / runtime dependencies (fast cadence)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: daily
      time: "06:00"
    labels: ["deps", "security"]
    open-pull-requests-limit: 5
    groups:
      security-critical:
        applies-to: security-updates
        patterns:
          - "*"

  # 2. General dev & tooling dependencies (batched weekly)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: weekly
      day: sunday
      time: "07:00"
      timezone: "America/Chicago"
    labels: ["deps", "tooling"]
    open-pull-requests-limit: 5
    groups:
      dev-tooling:
        patterns:
          - "@types/*"
          - "eslint*"
          - "vitest"
          - "@testing-library/*"
          - "typescript*"
      vite-minors:
        patterns:
          - "vite"
          - "@vitejs/*"
        update-types:
          - "minor"
          - "patch"
    ignore:
      - dependency-name: "react"
        update-types: ["version-update:semver-major"]
      - dependency-name: "typescript"
        update-types: ["version-update:semver-major"]

  # 3. GitHub Actions workflow dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly
