version: 2
updates:
  # Single npm config (Dependabot requires unique ecosystem+directory). We use groups to manage cadence.
  # NOTE: We cannot have separate schedules for security vs tooling without a different target-branch, so we
  # choose a daily cadence; tooling noise is minimized via grouping.
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: daily
      time: "06:00"
    open-pull-requests-limit: 8
    labels: ["deps"]
    groups:
      security-critical:
        applies-to: security-updates
        patterns:
          - "*"
      dev-tooling:
        patterns:
          - "@types/*"
          - "eslint*"
          - "vitest"
          - "@testing-library/*"
          - "typescript*"
      vite-minors:
        patterns:
          - "vite"
          - "@vitejs/*"
        update-types:
          - "minor"
          - "patch"
    ignore:
      - dependency-name: "react"
        update-types: ["version-update:semver-major"]
      - dependency-name: "typescript"
        update-types: ["version-update:semver-major"]

  # GitHub Actions updates (weekly)
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly
